/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.online.ordering.system.kafka.order.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum ShopOrderStatus implements org.apache.avro.generic.GenericEnumSymbol<ShopOrderStatus> {
  PAID  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ShopOrderStatus\",\"namespace\":\"com.online.ordering.system.kafka.order.avro.model\",\"symbols\":[\"PAID\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
